---
- name: Install required packages
  apt:
    name:
      - postfix
      - mailutils
      - dovecot-imapd
      - dovecot-pop3d
    state: present
    update_cache: yes

- name: Create virtual mail directory
  file:
    path: /var/mail/vhosts/grants.qfab.org
    state: directory
    owner: vmail
    group: vmail
    mode: '0750'

- name: Create virtual mailbox map
  copy:
    content: |
      # Virtual mailbox mappings
      @grants.qfab.org grants.qfab.org/
    dest: /etc/postfix/vmailbox
    owner: root
    group: root
    mode: '0644'

- name: Create virtual alias map
  copy:
    content: |
      # Virtual alias mappings
      postmaster@grants.qfab.org postmaster
    dest: /etc/postfix/virtual
    owner: root
    group: root
    mode: '0644'

- name: Create postmap databases
  command: postmap {{ item }}
  args:
    creates: "{{ item }}.db"
  with_items:
    - /etc/postfix/vmailbox
    - /etc/postfix/virtual

- name: Configure Postfix main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  notify: restart postfix

- name: Configure Postfix master.cf
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: '0644'
  notify: restart postfix

- name: Ensure Postfix service is running and enabled
  service:
    name: postfix
    state: started
    enabled: yes