---
- name: Deploy Postfix Mail Server
  hosts: mail_servers
  become: true
  roles:
    - postfix
  vars_files:
    - group_vars/vars.yml
  post_tasks:
    - name: Add ubuntu user to vmail group
      user:
        name: ubuntu
        groups: vmail
        append: yes
    - name: Find all inbox directories recursively
      ansible.builtin.find:
        paths: "{{ postfix_inbox_dir }}"
        file_type: directory
      register: inbox_dirs
    - name: Set mode 0750 on inbox dirs
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: '0750'
      loop: "{{ inbox_dirs.files }}"
